//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoomsFeatures
    {
        public int Id_HotelRoomFeatures { get; set; }
        public int Id_HotelRoom { get; set; }
        public string Description { get; set; }
    
        public virtual HotelRooms HotelRooms { get; set; }


        public static void AddFeaturesRoom(string FeturesDesc, int IdRoom)
        {
            HotelManagementDbContext hotelManagementDbContext = new HotelManagementDbContext();
            HotelRoomsFeatures hotelRoomsFeatures = new HotelRoomsFeatures()
            {
                Id_HotelRoom = IdRoom,
                Description = FeturesDesc
            };
            hotelManagementDbContext.HotelRoomsFeatures.Add(hotelRoomsFeatures);
            hotelManagementDbContext.SaveChanges();
        }
    }
}
