//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotels()
        {
            this.HotelRooms = new HashSet<HotelRooms>();
        }
    
        public int Id_UserHotel { get; set; }
        public string HotelName { get; set; }
        public string HotelCity { get; set; }
        public string PostalCodeHotel { get; set; }
        public string StreetHotel { get; set; }
        public string BuildingNumberHotel { get; set; }
        public string EmailHotel { get; set; }
        public string MainPhoneHotel { get; set; }
        public string DescriptionHotel { get; set; }
        public string WebsiteHotel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRooms> HotelRooms { get; set; }
    }
}
