//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRooms()
        {
            this.HotelRoomsFeatures = new HashSet<HotelRoomsFeatures>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int Id_HotelRoom { get; set; }
        public int Id_UserHotel { get; set; }
        public Nullable<int> NumberInUserHotel { get; set; }
        public string NameOfRoom { get; set; }
        public int Id_Condition { get; set; }
        public Nullable<double> CostOfRent { get; set; }
        public string OverallDescription { get; set; }
        public string OverallDescriptionAdditional { get; set; }
        public Nullable<double> RoomSurface { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<bool> WithBadroom { get; set; }
        public Nullable<int> QtyOfPersonsInRoom { get; set; }
    
        public virtual ConditionsOfHotelRooms ConditionsOfHotelRooms { get; set; }
        public virtual Hotels Hotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRoomsFeatures> HotelRoomsFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
